name: Sync Overleaf to GitHub
on:
  schedule:
    - cron: '0 * * * *' # 每小時執行一次，可調整頻率
  workflow_dispatch:
jobs:
  sync-overleaf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Configure git user
        run: |
          git config --global user.name "dong881"
          git config --global user.email "minghunghsu.taiwan@gmail.com"
      - name: Clone Overleaf project
        env:
          OVERLEAF_ID: ${{ secrets.OVERLEAF_ID }}
          OVERLEAF_TOKEN: ${{ secrets.OVERLEAF_TOKEN }}
        run: |
          git clone https://git:${OVERLEAF_TOKEN}@git.overleaf.com/${OVERLEAF_ID} overleaf
      - name: Sync Overleaf to GitHub
        run: |
          cd overleaf
          git remote add github https://github.com/dong881/MingThesis.git
          git pull overleaf master
          git push github master
